# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OnTime Development Blog
description: OnTime Github Pages!
baseurl: / # the subpath of your site, e.g. /support
url: https://ontime-git.github.io # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: 당신이 전문가! 
use_authors: true #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: OnTime
header: 당신의 지식이 세상에 도움이 되도록
subheader: |+
           우리는 카더라 지식공유 플랫폼을 통해 정보 공유 방식을 새롭게 정의합니다.
           
           친한 사람의 정보는 전문인 지식보다 유용하다, 우리가 나보다 똑똑하다는 신념을 믿습니다.
           
           이를 통해 누구나 자신의 지식을 공유하여 형성된 집단지성으로 보다 나은 세상으로 나아가길 바랍니다.

# meta_image: odin-meta.png

# Social Links
twitter_username: 
facebook_page:
github_username: ontime-git
email: cychoi@gmail.com
linkedin_page:
instagram_username: 


# Navivation
nav_item_one: Github
nav_item_one_link: https://github.com/ontime-git/

nav_item_two: Facebook
nav_item_two_link: 

nav_item_three: #
nav_item_three_link: #

nav_button: Return to OnTime Home
nav_button_link: https://ontime-git.github.io/

# More Help
help_one_title: Deep Learning Product
help_one_content: 딥비전, 금융/보험 OCR, 우편물 주소인식 등
help_one_button: Product
help_one_link: https://github.com/ontime-git/

help_two_title: Knowledge Sharing Platform
help_two_content: 이사/인테리어 견적 플랫폼, 아이가 아파요 플랫폼 .
help_two_button: Platform
help_two_link: https://github.com/ontime-git/

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
